#!/bin/bash

source /etc/os-release

creset="\e[0m"
cat="\e[1;30m"
cateyes="\e[1;33m"

newUrl=""
newUrl=$HOME_URL
newUrl=${newUrl/https:\/\//}
newUrl=${newUrl/http:\/\//}
newUrl=${newUrl##www.}
newUrl=${newUrl%%\/}


function getEnv() {
	newEnv=""
	newEnv=$XDG_CURRENT_DESKTOP
	[ -n "$newEnv" ] && return 0
	newEnv="none"
}


function getPkgs() {
	newPkgs="0"
	[ -f /bin/dpkg ] && newPkgs="$(dpkg --get-selections | wc -l)" && return 0
	[ -f /bin/pacman ] && newPkgs="$(pacman -Q | wc -l)" && return 0
	[ -f /bin/rpm ] && newPkgs="$(rpm -qa | wc -l)" && return 0
	[ -f /bin/xbps-query ] && newPkgs="$(xbps-query -l | wc -l)" && return 0
}

function getMorePkgs() {
	[ -f /bin/flatpak ] && newPkgs="${newPkgs}, $(flatpak list | wc -l) flatpaks"
	[ -f /bin/snap ] && newPkgs="${newPkgs}, $(snap list | wc -l) snaps"
	appimages="$(ls -1 ~/.local/bin/*.AppImage 2> /dev/null | wc -l)"
	[ $appimages != "0" ] && newPkgs="${newPkgs}, ${appimages} appimages"
}


getEnv
getPkgs
getMorePkgs

echo -e "\e[1;32mWelcome to $newUrl, $USER :D"
echo
echo -e "\e[1;31mdistro$creset  $PRETTY_NAME"
echo -e "\e[1;33mkernel$creset  $(uname -sr)"
echo -e "\e[1;32march$creset    $(uname -m)"
echo -e "\e[1;36mshell$creset   $(basename $SHELL)"
echo -e "\e[1;34menv$creset     $newEnv$creset"
echo -e "\e[1;35muptime$creset $(uptime -p | awk '{$1="";print $0}')"
echo -e "\e[1;30mpacks$creset   $newPkgs$creset"
echo -e "$cat
 ╱|
(${cateyes}˚${cat}ˎ ${cateyes}。${cat}7
|    〵
ししˍ,)ノ${creset}"